version: "3.8"
services:
  qdrant:
    image: qdrant/qdrant:v1.11.0
    container_name: qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_data:/qdrant/storage
    environment:
      - QDRANT__SERVICE__GRPC_PORT=6334
  neo4j:
    image: neo4j:5.22
    container_name: neo4j
    ports:
      - "7474:7474"   # Browser UI
      - "7687:7687"   # Bolt
    environment:
      - NEO4J_AUTH=neo4j/neo4j_password
      - NEO4J_PLUGINS=[]
    volumes:
      - ./neo4j_data:/data

